### PR TITLE
Made space for backup options in settings

### PR DESCRIPTION
**Pull request by issacnitin**
Action bar is not enabled as of now. If that needs to be done in a dead end Activity like this as well, please inform me. Also my first PR, git mistakes may have happened :cry:

### CODE REVIEW

**Comment by PaoloRotolo** [comment]
Hi @issacnitin. Looks good, but can you please undo all your changes in AndroidManifest and build.gradle?

**Comment by issacnitin** [comment]
Hi,
I've undo-ed all changes in build.gradle and AndroidManifest.xml except those which are necessary in AndroidManifest.xml.
I don't understand why the checks are failing. Could I get an insight into this travis-ci?

**Comment by PaoloRotolo** [comment]
Log line 1503:
https://travis-ci.org/Glucosio/android/builds/86645118#L1503

```[Fatal Error] :12:1: Element type "application" must be followed by either attribute specifications, ">" or "/>".```

Probably a minor syntax typo in Manifest. Are you using Android Studio? Try to build your code to better debug issues. :)

**Comment by issacnitin** [comment]
Yes I'm using Android studio. My fault, forgot to add a file before committing lol. Thank You for being patient.

**Comment by PaoloRotolo** [comment]
Merged, thank you!

**Pull request merged**
