### PR TITLE
Fix error - After merge, compile and run i get exception on start application

### PR DESCRIPTION
**Pull request by dmvstar**
After merge, compile and run i get exception on start application
1 avoid  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
10-02 23:57:28.285 3596-3596/org.glucosio.android E/AndroidRuntime:     at org.glucosio.android.tools.GlucoseRanges.<init>(GlucoseRanges.java:15)

2 upgrade database
Caused by: android.database.sqlite.SQLiteException: no such column: preferred_range (code 1): , while compiling

### CODE REVIEW

**Comment by bkerensa** [comment]
I'm confused are you reporting a bug or doing a pull request? @PaoloRotolo can you follow up on this.

**Comment by dmvstar** [comment]
After detect bug i make pull request for fix it

**Comment by PaoloRotolo** [comment]
Hey @dmvstar. I changed the dB structure yesterday. You should just remove and install Glucosio again.
We'll start adding dB versions in prod.

**Comment by dmvstar** [comment]
Ok

**Pull request closed without merging**
