### PR TITLE
correct and update ru translation strings

### PR DESCRIPTION
**Pull request by dmvstar**
correct and update ru translation strings for <array name="tips_all">

### CODE REVIEW

**Comment by bkerensa** [comment]
@dmvstar This change should be made on http://translate.glucosio.org

**Comment by dmvstar** [comment]
Ok
Thanks
When you planed merging translation to main branch (for example - ru translation is completed)

**Comment by bkerensa** [comment]
@dmvstar Probably on Sunday as we are waiting for other languages to be merged in and we do it all at once with one push.

**Comment by dmvstar** [comment]
Thanks, waiting.

**Pull request closed without merging**
